# ==============================================
# PostgreSQL DataSource
# ==============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/yugiohdb
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

# ==============================================
# JPA / Hibernate
# ==============================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

# ==============================================
# Server
# ==============================================
server.port=8080
gemini.api.key=AIzaSyC8CZtOFE-O9VF_-FbEbknumIhCWDghHaw  

# Web Logging
# logging.level.org.springframework.web=DEBUG
# logging.level.org.hibernate.orm.jdbc.bind=trace
# logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace